# Generated by Django 5.2.6

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(help_text='ID único del evento en Google Calendar', max_length=255, unique=True, verbose_name='ID de Evento de Google')),
                ('meet_link', models.URLField(help_text='URL de la videollamada de Google Meet', verbose_name='Link de Google Meet')),
                ('invited_emails', models.JSONField(default=list, help_text='Lista de correos electrónicos de los invitados', verbose_name='Emails Invitados')),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio programada', null=True, verbose_name='Inicio Programado')),
                ('scheduled_end', models.DateTimeField(blank=True, help_text='Fecha y hora de fin programada', null=True, verbose_name='Fin Programado')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SCHEDULED', 'Scheduled'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='CREATED', help_text='Estado actual de la reunión', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('organizer', models.ForeignKey(help_text='Usuario que crea/organiza la reunión', on_delete=django.db.models.deletion.PROTECT, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(blank=True, help_text='ID del archivo de grabación en Google Drive', max_length=255, null=True, verbose_name='ID de Archivo en Drive')),
                ('drive_file_url', models.URLField(blank=True, help_text='URL directa al archivo de grabación', null=True, verbose_name='URL del Archivo en Drive')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duración de la grabación en segundos', null=True, verbose_name='Duración (segundos)')),
                ('available_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que la grabación estuvo disponible', null=True, verbose_name='Disponible Desde')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('meeting', models.OneToOneField(help_text='Reunión a la que pertenece esta grabación', on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='meetings.meeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Grabación de Reunión',
                'verbose_name_plural': 'Grabaciones de Reuniones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Correo electrónico del participante', max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('guest', 'Guest')], default='guest', help_text='Rol del participante en la reunión', max_length=20, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('meeting', models.ForeignKey(help_text='Reunión a la que pertenece este participante', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['created_at'],
                'unique_together': {('meeting', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['google_event_id'], name='meetings_me_google__8c0a87_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status'], name='meetings_me_status_1a5e02_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['-created_at'], name='meetings_me_created_0e8b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['email'], name='meetings_pa_email_e1c84c_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['meeting', 'email'], name='meetings_pa_meeting_21a5ce_idx'),
        ),
    ]

